<?php

class Validation {
    static $TEXT = "TEXT_VALIDATION";
    static $PHONENUMBER = "PHONENUMBER";
    static $EMAIL = "EMAIL_VALIDATION";
    static $PWD = "PWD_VALIDATION";
    static $USERNAME = "USERNAME_VALIDATION";
    static $USERLOGIN = "USERLOGIN_VALIDATION";
    static $CATEGORYEXISTS = "CATEGORYEXISTS_VALIDATION";
    static $EMAILINUSE = "EMAILINUSE_VALIDATION";
    static $IDINUSE = "IDINUSE_VALIDATION";
    static $VALIDID = "VALIDID_VALIDATION";
    static $VALIDUSERPROFILEPICTURE = "VALIDUSERPROFILEPICTURE_VALIDATION";
}